### ISSUE TITLE
TypeError: cannot read property 'Store' 

### ISSUE THREAD

**Issue by PleasantPro** [cythilya/NodeJS-Microblog#1]
I was going to install this program, but I met a problem of TypeError: Cannot read property 'Store' 
![Uploading store.PNG…]()

**Comment by PleasantPro** [comment]
![store](https://cloud.githubusercontent.com/assets/11971721/8396554/9e49d29a-1ddd-11e5-824b-4698e71d4007.PNG)I was going to paste the error message picture here. But it can't be displayed.

**Comment by ldez** [comment]
I do following commands:

``` shell
git clone https://github.com/cythilya/NodeJS-Microblog.git
cd NodeJS-Microblog\microblog\
npm install
npm install ejs --save
npm start
```

And I repoduce your first bug:

``` text
module.js:338
    throw err;
          ^
Error: Cannot find module 'bytes'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\data\NodeJS-Microblog\microblog\node_modules\express\node_modules\connect\lib\utils.js:393:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

After I do:

``` shell
npm cache clean
npm install express --save
npm start
```

The server start correctly, go to http://localhost:3000/ and it's works.
I can create an account and post a message.

**Comment by ldez** [comment]
I do not speak Chinese, so I cannot read the article or really use the site.

Please close https://github.com/npm/npm/issues/8726

**Comment by PleasantPro** [comment]
Hi Idez, I met another problem when coding with nodejs. I can't write down in this issue to u. Can you please give me your mailbox? I will write it in details for your help. Anyway, I appreciate you very much for the help you extended. I must know your contact address and reward you. Thank you very much.
